% ============================================================
% calculations.pl
% Movie Recommendation Expert System
% Compatibility Calculation Layer
% ============================================================
%
% PURPOSE
% -------
% Convert the individual compatibility contributions generated by
% compatibility_rules.pl into a raw score and a normalized score.
%
% Normalization uses a comparable ceiling: the total weight of the
% preferences this movie can answer. A preference counts only when
% the same movie fact the compatibility rules call is present.
% Missing data drops out of that ceiling, so it does not shrink the
% score. A known comparison that scores 0 stays in the ceiling.
% user_max_compatibility/2 remains the full profile total and is
% not the divisor.
%
% Processing order:
%   1. Check whether the movie passes hard constraints
%   2. Collect all compatibility contributions once
%   3. Derive positive, negative, and raw scores from that list
%   4. Build the comparable ceiling for this movie
%   5. Turn the raw score into an unclamped percentage
%   6. Clamp that percentage to a displayed 0-100 score
%   7. Rank by the unclamped percentage, then by the raw score
%
% IMPORTANT
% ---------
% This file does NOT:
% - Apply preference strength
% - Calculate confidence
% - Apply novelty/diversity meta-rules
% - Produce natural-language explanations
%
% ============================================================


% ============================================================
% 1. BASE WEIGHTS
% ============================================================

preference_weight(genre, 3).
preference_weight(subgenre, 4).
preference_weight(runtime, 3).
preference_weight(year, 2).
preference_weight(decade, 2).
preference_weight(age_rating, 1).
preference_weight(language, 2).
preference_weight(actor, 2).
preference_weight(director, 3).
preference_weight(producer, 1).
preference_weight(character, 2).
preference_weight(theme, 3).
preference_weight(humor, 2).
preference_weight(realism, 2).
preference_weight(pace, 3).
preference_weight(gore, 3).
preference_weight(violence, 2).
preference_weight(popularity, 2).
preference_weight(trending, 1).
preference_weight(character_archetype, 3).


% ============================================================
% 2. MOVIE FACTS THE RULES CAN ANSWER
% ============================================================
%
% A category is comparable when the movie fact that category's
% rules already call is present. Gore medium against low is still
% an answer. An absent gore fact is not. Trending unknown is
% unrecorded, so it is not an answer either.

movie_fact_available(genre, Movie) :-
    once(genre(Movie, _)).

movie_fact_available(subgenre, Movie) :-
    once(subgenre(Movie, _)).

movie_fact_available(runtime, Movie) :-
    once(runtime(Movie, _)).

movie_fact_available(year, Movie) :-
    once(release_year(Movie, _)).

movie_fact_available(decade, Movie) :-
    once(decade(Movie, _)).

movie_fact_available(age_rating, Movie) :-
    once(age_rating(Movie, _)).

movie_fact_available(language, Movie) :-
    once(original_language(Movie, _)).

movie_fact_available(actor, Movie) :-
    once(actor(Movie, _)).

movie_fact_available(director, Movie) :-
    once(director(Movie, _)).

movie_fact_available(producer, Movie) :-
    once(producer(Movie, _)).

movie_fact_available(character, Movie) :-
    once(character(Movie, _)).

movie_fact_available(theme, Movie) :-
    once(theme(Movie, _)).

movie_fact_available(humor, Movie) :-
    once(humor_level(Movie, _)).

movie_fact_available(realism, Movie) :-
    once(realism(Movie, _)).

movie_fact_available(pace, Movie) :-
    once(pace(Movie, _)).

movie_fact_available(gore, Movie) :-
    once(gore_level(Movie, _)).

movie_fact_available(violence, Movie) :-
    once(violence_level(Movie, _)).

movie_fact_available(popularity, Movie) :-
    once(market_position(Movie, _)).

movie_fact_available(trending, Movie) :-
    once((
        trending_status(Movie, Status),
        Status \= unknown
    )).

movie_fact_available(character_archetype, Movie) :-
    once(character_archetype(Movie, _)).


% ============================================================
% 3. RAW COMPATIBILITY CONTRIBUTIONS
% ============================================================

% Identical Reason-Points pairs are kept once, so a duplicated
% movie fact cannot award the same rule twice. setof/3 fails when
% nothing matches, and the second clause turns that into an empty
% list. Both clauses still require eligibility, so a rejected movie
% does not become a zero score.

compatibility_contributions(User, Movie, Contributions) :-
    eligible_movie(User, Movie),
    setof(
        Reason-Points,
        compatibility(User, Movie, Reason, Points),
        Contributions
    ),
    !.

compatibility_contributions(User, Movie, []) :-
    eligible_movie(User, Movie),
    !.


% ============================================================
% 4. POSITIVE, NEGATIVE, AND RAW SCORES
% ============================================================
%
% All three sums come from one contribution list. NegativeScore
% in movie_compatibility_summary/8 is the signed sum of the
% negative contributions (for example -3, not 3).

positive_compatibility_score(User, Movie, Score) :-
    compatibility_sums(User, Movie, Score, _, _).

negative_compatibility_score(User, Movie, Score) :-
    compatibility_sums(User, Movie, _, Score, _).

raw_compatibility_score(User, Movie, Score) :-
    compatibility_sums(User, Movie, _, _, Score).

compatibility_sums(User, Movie, Positive, Negative, Raw) :-
    compatibility_contributions(User, Movie, Contributions),
    sum_contributions(Contributions, 0, 0, Positive, Negative),
    Raw is Positive + Negative.

sum_contributions([], Positive, Negative, Positive, Negative).

sum_contributions([_-Points|Rest], Positive0, Negative0, Positive, Negative) :-
    accumulate_point(Points, Positive0, Negative0, Positive1, Negative1),
    sum_contributions(Rest, Positive1, Negative1, Positive, Negative).

accumulate_point(Points, Positive0, Negative, Positive, Negative) :-
    Points > 0,
    !,
    Positive is Positive0 + Points.

accumulate_point(Points, Positive, Negative0, Positive, Negative) :-
    Points < 0,
    !,
    Negative is Negative0 + Points.

accumulate_point(_, Positive, Negative, Positive, Negative).


% ============================================================
% 5. MAXIMUM POSSIBLE USER SCORE
% ============================================================
%
% Full profile total. Scoring does not divide by this value.

user_max_compatibility(User, MaxScore) :-
    findall(
        Weight,
        (
            preference(User, Category, Value),
            scored_preference(Category, Value, Weight)
        ),
        Weights
    ),
    sum_list(Weights, MaxScore).


scored_preference(Category, _, Weight) :-
    Category \= trending,
    preference_weight(Category, Weight).

scored_preference(trending, neutral, 0).

scored_preference(trending, Value, Weight) :-
    Value \= neutral,
    preference_weight(trending, Weight).


% ============================================================
% 6. COMPARABLE CEILING
% ============================================================
%
% Preferences this movie can answer. Trending neutral has weight
% 0, so it contributes nothing. A zero from a real comparison,
% such as gore medium against low, stays in the total.

comparable_ceiling(User, Movie, Ceiling) :-
    findall(
        Weight,
        (
            preference(User, Category, Value),
            movie_fact_available(Category, Movie),
            scored_preference(Category, Value, Weight)
        ),
        Weights
    ),
    sum_list(Weights, Ceiling).


% ============================================================
% 7. NORMALIZED COMPATIBILITY SCORE
% ============================================================
%
% compatibility_score/3 is the displayed 0-100 value.
% A score exists only for an eligible movie.

compatibility_score(User, Movie, Score) :-
    eligible_movie(User, Movie),
    raw_compatibility_score(User, Movie, RawScore),
    comparable_ceiling(User, Movie, Ceiling),
    normalize_compatibility(RawScore, Ceiling, Score).


normalize_compatibility(RawScore, Ceiling, Score) :-
    unclamped_percentage(RawScore, Ceiling, Percentage),
    clamp_percentage(Percentage, Clamped),
    Score is round(Clamped).


unclamped_percentage(_, 0, 0) :-
    !.

unclamped_percentage(RawScore, Ceiling, Percentage) :-
    Percentage is (RawScore / Ceiling) * 100.


% ============================================================
% 8. SCORE CLAMPING
% ============================================================

clamp_percentage(Value, 0) :-
    Value < 0,
    !.

clamp_percentage(Value, 100) :-
    Value > 100,
    !.

clamp_percentage(Value, Value).


% ============================================================
% 9. COMPATIBILITY SUMMARY
% ============================================================
%
% MaxScore is this movie's comparable ceiling, not the full
% profile total from user_max_compatibility/2.
% NegativeScore is the signed sum of the negative contributions
% (for example -3, not 3).

movie_compatibility_summary(
    User,
    Movie,
    RawScore,
    MaxScore,
    NormalizedScore,
    PositiveScore,
    NegativeScore,
    Reasons
) :-
    eligible_movie(User, Movie),
    compatibility_sums(
        User,
        Movie,
        PositiveScore,
        NegativeScore,
        RawScore
    ),
    comparable_ceiling(User, Movie, MaxScore),
    normalize_compatibility(RawScore, MaxScore, NormalizedScore),
    compatibility_reasons(User, Movie, Reasons).


% ============================================================
% 10. SCORE BREAKDOWN
% ============================================================
%
% One query for development and demonstration:
%
%   ?- score_breakdown(user1, scream, X).

score_breakdown(User, Movie, Breakdown) :-
    movie_compatibility_summary(
        User,
        Movie,
        Raw,
        Max,
        Score,
        Positive,
        Negative,
        Reasons
    ),
    Breakdown = breakdown(
        raw(Raw),
        maximum(Max),
        score(Score),
        positive(Positive),
        negative(Negative),
        reasons(Reasons)
    ).


% ============================================================
% 11. MOVIE-SCORE PAIRS
% ============================================================

movie_score(User, Movie, Score) :-
    movie(Movie),
    compatibility_score(User, Movie, Score).


% ============================================================
% 12. RANK ALL ELIGIBLE MOVIES
% ============================================================
%
% Sort by the unclamped percentage, then by the raw score.
% Negated keys make keysort return the best movie first.
% The pairs still carry the clamped 0-100 display score, so two
% movies can both display 0 while the less negative one ranks
% higher.

ranked_movies(User, RankedMovies) :-
    findall(
        (NegPercentage-NegRaw)-(Score-Movie),
        (
            movie(Movie),
            raw_compatibility_score(User, Movie, RawScore),
            comparable_ceiling(User, Movie, Ceiling),
            unclamped_percentage(RawScore, Ceiling, Percentage),
            normalize_compatibility(RawScore, Ceiling, Score),
            NegPercentage is -Percentage,
            NegRaw is -RawScore
        ),
        KeyedMovies
    ),
    keysort(KeyedMovies, Sorted),
    unkey_ranked_movies(Sorted, RankedMovies).


unkey_ranked_movies([], []).

unkey_ranked_movies([_-Pair|Rest], [Pair|Ranked]) :-
    unkey_ranked_movies(Rest, Ranked).


% ============================================================
% 13. TOP-N RECOMMENDATIONS
% ============================================================

top_movies(User, N, TopMovies) :-
    integer(N),
    N >= 0,
    ranked_movies(User, RankedMovies),
    take_first(N, RankedMovies, TopMovies).


take_first(0, _, []) :-
    !.

take_first(_, [], []) :-
    !.

take_first(N, [Head|Tail], [Head|Result]) :-
    N > 0,
    Next is N - 1,
    take_first(Next, Tail, Result).
